spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: response-body-advice-example
  datasource:
    url: jdbc:mysql://localhost:3306/basquiat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000
      maximum-pool-size: 10
      pool-name: basquiat-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8761

---
## do other profile setting